//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_Producto { get; set; }
        public string nombreProducto { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string precio { get; set; }
    }
}
